FROM node:lts-alpine

WORKDIR /app

RUN npm install -g turbo pnpm

COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./ 
COPY turbo.json ./ 
COPY package.json ./ 

COPY apps/api/package.json ./apps/api/
COPY apps/parallel/package.json ./apps/parallel/
COPY packages/eslint-config/package.json ./packages/eslint-config/
COPY packages/typescript-config/package.json ./packages/typescript-config/
COPY packages/ui/package.json ./packages/ui/

RUN pnpm install --recursive

COPY . .

CMD ["pnpm", "dev"]
